### ISSUE TITLE
Syslog error when clicking cancel on the password prompt

### ISSUE THREAD

**Issue by dmulder** [dmulder/yast-aduc#1]
Broadcast message from systemd-journald@linux-4a0j (Wed 2017-10-18 06:30:35 MDT):

aduc.py[28372]: argument 2 must be string or read-only buffer, not None

**Comment by noelpower** [comment]
This is all related to the change in how the credentials are handled (kdc dependency removal). We should decide whether Null credential (or password in this case) is acceptable or not.

Note: The same problem occurs in gpmc the only difference is the exception isn't logged to syslog.

If the old credential handling is used we default to machine credentials, the new code seems to default to a user who runs and no password. Might be worth looking to see if that defaulting can be exercised, alternatively we could just error out and close if we don't have a username and password
